### ISSUE TITLE
Support Fhem 5.8, new auth token

### ISSUE THREAD

**Issue by ManOki** [klassm/andFHEM#1099]
Hello,

i updated to Fhem 5.8 and now andFhem cannot read any devices from my instance.
Here is the forum post: https://forum.fhem.de/index.php/topic,67419.0.html

Greets, ManOki

**Comment by klassm** [comment]
Hi,

Thanks for the info. Please disable the attribute for now. There won't be a fix before next weekend.

Matthias

**Comment by ManOki** [comment]
Ok, thanks for the hint.

disabled it with `attr WEB csrfToken none`.

**Comment by klassm** [comment]
The next version will support the csrf token. However, the implementation is pretty ugly because FHEMWEB enforces the token to be provided for _every_ request, including only reading ones. This makes it impossible to determine whether I need to provide a token or not. To make it even worse, FHEMWEB does not respond with an error when the token is wrong but pretends to execute the command even though.

Effectively andFHEM will now call an "unprotected" URL of FHEMWEB before _every_ request and try to try to find out the token. Effectively this doubles the amount of required requests...

**Comment by petterpet** [comment]
I added a static token with 15 characters. Since that, my andFHEM App isn't able to connect to my server.
How can I tell the app this token?
Or is there any other solution to fix the connection?

**Comment by klassm** [comment]
Well - actually it shouldn't make any difference. AndFHEM obtains the token by sending a request without token to "$serverUrl?room=notExistingJustToLoadCsrfToken" and then extracts the token from the response. Using this token the actual request is then sent - so this really should not depend on static vs dynamic tokens.
I just tried to set the token manually to "abcdefghijklmnopqrstuvxyz" - andFHEM could still connect and request an xmllist.

**Comment by petterpet** [comment]
I tried without a token and with an dynamic. In both cases I was able to connect.
Than I tried with another static ones - and it works. But my old token still not.

But if I leave out the "%", andFHEM is able to connect. 
So my App is working again!
Thank's for help.

**Comment by klassm** [comment]
Thanks for the hint @petterpet - percent signs really don't work. I've fixed this in #1314 - will be released with the next version.
