### ISSUE TITLE
GCM messaging not stable with Android 8

### ISSUE THREAD

**Issue by cyberman54** [klassm/andFHEM#1166]
I ran in problems using 98_gcmsend messaging with fhem & andFHEM.
Messaging worked very realiable for some years. Now i got the Android 8 "Oreo" update on my Google Pixel. Since then gcm messages sometimes do not appear on the pixel, but sometimes they do with some seconds delay.

**Comment by klassm** [comment]
Thanks for the issue. Do you use the latest version of andfhem? This is
4.6.9. Did you enable the notification channel explicitly within the
Android app preferences for andfhem?

Matthias

Am 17.09.2017 21:01 schrieb "Cyberman" <notifications@github.com>:

**Comment by cyberman54** [comment]
4.6.9  = yes
All notification settings in Android set explicitly for andFHEM

**Comment by cyberman54** [comment]
After restart of fhem server and smartphone still no more gcm push messages von Android 8 smartphone.
gcm_send filelog on fhem reports that send command was executed.
Is there any possibility on Google firebase console to further debug transfer of push messages?

**Comment by klassm** [comment]
@cyberman54 I suppose this is pretty much of a different issue. As GCM support for andFHEM was built some time ago, it has been compiled against an API which has been deprecated since. The service has been migrated to FCM (firebase cloud messaging), whereas the API is still somehow compatible, but in reality is still different.
What I did is migrate andFHEM from the GCM API to the FCM API, so that the cloud version and the API version in andFHEM match.
Unfortunately, I still don't own an Oreo device, so that I am not able to test whether it works by now on Oreo - at least, the emulator still does not show any FCM messages (I don't know whether it ever will, as it is only an emulator ...)

However, this migration has some consequences:
* Installation becomes much more simple, as you do not have do specify a project number any more (this is done internally and seems to work quite well)
* You will have to update the gcmsend plugin, as it sends messages to a different endpoint
* You will have to re-register all devices using the new registration id created by Firebase and no longer by GCM

I'll release the change with the next version. It would be great if you could test whether fcm works then.

**Comment by cyberman54** [comment]
yes, of course i will test it. Thanks for migration to firebase.

**Comment by cyberman54** [comment]
Migrated GCM to FCM, first tests positive! 
Messaging now seems working again with Android 8.0 ! Thanks for migration. 

Notes:
- i had to install additional perl modules Crypt::CBC and CryptX on my raspberry pi
- new 98_gcmsend.pm shows some perl warnings in logfile

2017.09.24 23:51:04 1: PERL WARNING: Scalar value @a[1] better written as $a[1] at ./FHEM/98_gcmsend.pm line 35, <$fh> line 483.
2017.09.24 23:51:04 1: PERL WARNING: Scalar value @a[$i] better written as $a[$i] at ./FHEM/98_gcmsend.pm line 45, <$fh> line 483.
2017.09.24 23:51:04 1: PERL WARNING: Scalar value @array[$i] better written as $array[$i] at ./FHEM/98_gcmsend.pm line 79, <$fh> line 483.
2017.09.24 23:51:04 1: PERL WARNING: Using a hash as a reference is deprecated at ./FHEM/98_gcmsend.pm line 195, <$fh> line 483.
2017.09.24 23:51:04 1: PERL WARNING: Using a hash as a reference is deprecated at ./FHEM/98_gcmsend.pm line 199, <$fh> line 483.
2017.09.24 23:51:04 1: PERL WARNING: Using a hash as a reference is deprecated at ./FHEM/98_gcmsend.pm line 201, <$fh> line 483.
2017.09.24 23:51:04 1: PERL WARNING: Scalar value @parts[0] better written as $parts[0] at ./FHEM/98_gcmsend.pm line 220, <$fh> line 483.
2017.09.24 23:51:04 1: PERL WARNING: Scalar value @parts[1] better written as $parts[1] at ./FHEM/98_gcmsend.pm line 221, <$fh> line 483.
2017.09.24 23:51:04 1: PERL WARNING: Scalar value @parts[2] better written as $parts[2] at ./FHEM/98_gcmsend.pm line 222, <$fh> line 483.
2017.09.24 23:51:04 1: PERL WARNING: Scalar value @parts[3] better written as $parts[3] at ./FHEM/98_gcmsend.pm line 225, <$fh> line 483.
2017.09.24 23:51:04 1: PERL WARNING: Scalar value @parts[3] better written as $parts[3] at ./FHEM/98_gcmsend.pm line 226, <$fh> line 483.
2017.09.24 23:51:04 1: PERL WARNING: Scalar value @parts[3] better written as $parts[3] at ./FHEM/98_gcmsend.pm line 229, <$fh> line 483.

**Comment by klassm** [comment]
Cool, thanks for the update!

Those crypt dependencies have been required by some previous update already, as andFHEM supports AES encryption of GCM content, so that Google cannot read those messages :-)

Yes, well those warnings ... I know of them and have not had any desire in fixing them ...
