### ISSUE TITLE
Widgets (Switches) don't gets updated trough incoming FCM

### ISSUE THREAD

**Issue by JorinL** [klassm/andFHEM#1194]
I have often the situation, that my mobile phone receives an FCM and it is even logged inside the FCM-History in andFHEM, but the widget stays on the previous state.

Please take a look onto that screenshots: https://drive.google.com/drive/folders/1i6zw9iZMyhiaJqb9we-XPTf0eBdteZfF?usp=sharing

It's not always, as far as I can say. 
I reduced my FCM traffic to a minimum.

**Comment by klassm** [comment]
Does it never get updates? Just tried it for normal toggle widgets - those get updated here. However, I did some more refactorings here, so this is not too reliable.

**Comment by JorinL** [comment]
I think it starts to break if you disable the option "Widget-Updates can fetch new data from server".
Then most of all switches miss the FCM triggered update.

But this option kills my batterie.

**Comment by klassm** [comment]
Ok I cannot reproduce this behaviour anymore. However, I don't really worry about that as the implementation for widget updates is more or less completly new within the next version.

In other words - I guess the problem was there but has been already solved in the new version. By the way - this reimplementation might also fix your battery issues.

Maybe you can just give me a hint here whether the new version solves your problems.

**Comment by JorinL** [comment]
Nice :-) !

**Comment by JorinL** [comment]
So i can provide feedback now:

After the last update I placed my widgets again and it seems to be fine - now some widgets are broken (not completely). I can tap on them and the device will be switched on and off. Also the fcm is received about the status update. But the received status is not used on the widget. If i place a new widget for the same device it works.

For me it seems like andFHEM has los the ID of the widget for updating its drawing (on/off).
I have saved the log file and found out that andFHEM is searching a widget for a device i never had applied as a widget (appears very often):

11-22 23:26:17.577 31267 29877 I DeviceAppWidgetView: creating appwidget view for WidgetConfiguration{widgetId=182, widgetType=STATUS, payload=[Romy.Anwesenheit], connectionId=Optional.of(46c09d4d-7aea-49af-a1d6-8ec37783b43c)}
11-22 23:26:17.579 31267 29877 E li.klass.fhem.AndFHEMApplication: Uncaught Exception detected in thread Thread[pool-1-thread-172,5,main]
11-22 23:26:17.579 31267 29877 E li.klass.fhem.AndFHEMApplication: java.lang.IllegalArgumentException: device cannot be found, device name = Romy.Anwesenheit
11-22 23:26:17.579 31267 29877 E li.klass.fhem.AndFHEMApplication: 	at li.klass.fhem.appwidget.ui.widget.base.DeviceAppWidgetView.createView(Unknown Source)
11-22 23:26:17.579 31267 29877 E li.klass.fhem.AndFHEMApplication: 	at li.klass.fhem.appwidget.update.AppWidgetInstanceManager.update(Unknown Source)
11-22 23:26:17.579 31267 29877 E li.klass.fhem.AndFHEMApplication: 	at li.klass.fhem.appwidget.update.AppWidgetUpdateService.updateWidget(Unknown Source)
11-22 23:26:17.579 31267 29877 E li.klass.fhem.AndFHEMApplication: 	at li.klass.fhem.appwidget.update.AppWidgetUpdateService.updateAllWidgets(Unknown Source)
11-22 23:26:17.579 31267 29877 E li.klass.fhem.AndFHEMApplication: 	at li.klass.fhem.fcm.receiver.FcmNotifyHandler.updateWidgets(Unknown Source)
11-22 23:26:17.579 31267 29877 E li.klass.fhem.AndFHEMApplication: 	at li.klass.fhem.fcm.receiver.FcmNotifyHandler.handleNotify(Unknown Source)
11-22 23:26:17.579 31267 29877 E li.klass.fhem.AndFHEMApplication: 	at li.klass.fhem.fcm.receiver.FcmService.onMessageReceived(Unknown Source)
11-22 23:26:17.579 31267 29877 E li.klass.fhem.AndFHEMApplication: 	at li.klass.fhem.fcm.receiver.FcmIntentService.onMessageReceived(Unknown Source)
11-22 23:26:17.579 31267 29877 E li.klass.fhem.AndFHEMApplication: 	at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(Unknown Source)
11-22 23:26:17.579 31267 29877 E li.klass.fhem.AndFHEMApplication: 	at com.google.firebase.iid.zzc.run(Unknown Source)
11-22 23:26:17.579 31267 29877 E li.klass.fhem.AndFHEMApplication: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
11-22 23:26:17.579 31267 29877 E li.klass.fhem.AndFHEMApplication: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
11-22 23:26:17.579 31267 29877 E li.klass.fhem.AndFHEMApplication: 	at java.lang.Thread.run(Thread.java:762)

Other errors are (even in an interval): 

11-22 23:23:56.305 31267 31267 V li.klass.fhem.fragments.core.BaseFragment$UIBroadcastReceiver: received action li.klass.fhem.constants.Actions.CONNECTION_ERROR_HIDE


Possible my app andFHEM config is broken?

**Comment by klassm** [comment]
Ok, I managed to get some things from your post:

* If a single appwidget update fails with an exception, all widget updating fails. This is bad (even if exceptions are not intended. I've now built it in a way a single failing widget update won't break the whole updating.
* If renaming a device, an exception was thrown as the device could not be found. This is bad - not some question marks are shown to indicate the device could not be found (instead of just throwing an exception).
* However, the original reason for this problem is that andFHEM won't detect that an appwidget does not exist anymore. There seem to be some cases where app widget ids just get lost - and the the configuration will be persisted forever. This configuration is used to update all appwidgets. This might really explain your battery issues, as you're device is requesting xmllists for devices that don't even exist anymore. Simple fix: delete all non existing widget configurations when updating all devices.

CONNECTION_ERROR_HIDE is not an error. That one just indicates that the connection error dialog within the app should be hidden. This one is always sent when a device list update succeeds.

Why andFHEM has a widget configuration for devices you don't know of? I have no idea. Are you really sure you _never_ created a widget configuration for this device?

**Comment by klassm** [comment]
Before releasing a new version with those fixes, I'd like to test the changes at least over one or two days ... just to make sure I did not break something even more :-)

**Comment by JorinL** [comment]
Hey nice that I could help revealing that :-)
And thanks for your time again! I appreciate seeing andFHEM getting better and better.

**Comment by JorinL** [comment]
Well, I still have the problem - if the hook "no new data from server with widget updates" is set off then sometimes Switches don't get updatet - I currently had a switch not correct set to off from 17:42 (fcm message is there and says off). 

The log did not capture that long backwards 22 o'clock was the end.

But I saw that even it update ist disabled many times in one minute this i started:

11-30 22:42:45.628 28264  6904 I *getUpdateIntentService: updateAllWidgets
11-30 22:42:48.453 28264  6904 I *getUpdateIntentService: updateAllWidgets
11-30 22:42:50.009 28264  6904 I *getUpdateIntentService: updateAllWidgets
11-30 22:42:56.222 28264  6904 I *getUpdateIntentService: updateAllWidgets
11-30 22:43:02.516 28264  6904 I *getUpdateIntentService: updateAllWidgets

Is that correct?

Energie consumption is much better! Thanks for the good work!

**Comment by klassm** [comment]
Hi @JorinL 

Are those log statesments consecutive or are some statements missing in between? I am wondering whether those widget updates are triggered via FCM/GCM messages.

Concerning the widgets not being updated - this might be caused by a totally different thing. The gcmsend module sends changes as list, which are then applied to the locally stored device list in andFHEM. If applying those changes fails (because for example attributes should be updated but states are) the widget would be wrong afterwards.
Updating the device list afterwards always serves as a kind of fallback to make sure the device lists are in sync.

Consequently, I am wondering whether you get this problem always for a specific device. If yes, I would be interested in an xmllist of that device and in the FHEM log posting that GCM change to Google (or just wait for the next version of andFHEM which logs some more data).

Matthias

**Comment by JorinL** [comment]
I only copied those update starts, I did send you the complete log yet.
