### ISSUE TITLE
stateFormat img tags not working

### ISSUE THREAD

**Issue by popy2k14** [klassm/andFHEM#1300]
I have a custom stateFormat like:

```
{
  my $state = ReadingsVal($name, "state", "nomotion");
  my $temp = sprintf("   %.2f °C", ReadingsVal($name,"temperature","0"));

  #icon
  my $text = '<div><img src="/fhem/images/openautomation/temp_temperature.svg" height="29" width="29">&nbsp;';
   
  #add temp
  $text = $text.$temp."&nbsp;&nbsp;";

  #add motion
  if($state eq "motion")
  {
  	$text = $text.'<img src="/fhem/images/openautomation/user_available.svg" height="29" width="29">&nbsp;';
  }else{
  	$text = $text.'<img src="/fhem/images/fhemSVG/people_sensor.svg" height="29" width="29">&nbsp;';
  }  
  
  #add end div
  $text = $text.'</div>';  
  
  return $text;
}
```

Sadly andFHEM do not display the images correctly, see:

![andfhem_screenshot_2018-12-05-22-24-07](https://user-images.githubusercontent.com/6324597/49546248-14323e80-f8e0-11e8-96c8-609a22208e0c.png)

And here is FHEM WEB, which displays it correctly:

![fhemweb_screenshot_2018-12-05-22-35-48](https://user-images.githubusercontent.com/6324597/49546249-14cad500-f8e0-11e8-91e3-b14d30a8127e.png)

Can you please fix this issue?

**Comment by klassm** [comment]
Hey @popy2k14 

Well, yes, you are certainly correct. However, I don't think this can be fixed in a sensible way. AndFHEM does not have a perl interpreter in any way - and I don't think it will ever have one. Even worse, you're perl function is calling other global functions - so andFHEM would have to emulate all that stuff to behave correctly.

Currently, those icons only work in a very regexp like manner (which is kind of language independent):
attr Rep.Agent devStateIcon connected:10px-kreis-gelb .*disconnect:10px-kreis-rot .*done:10px-kreis-gruen 

StateFormat is indirectly evaluated, as FHEM will set the evaluated property on the device - so andFHEM can use it - this does jot happen for icons.

In consequence, I am afraid that there's nothing I can currently do about this issue.

Matthias

**Comment by popy2k14** [comment]
Thanks, a lot for the detailed explanation.
Now its clear to me that there cant much be done on the andFHEM side.

Keep up the good work.
