### ISSUE TITLE
Switch to "configuration" let andFHEM freeze

### ISSUE THREAD

**Issue by janusjanusjanus** [klassm/andFHEM#940]
After starting the app a switch to the configuration (wrench icon) does nothing but freeze the app. A black screen follows. Only canceling the app is helpful.
This situation is reproducible.

**Comment by klassm** [comment]
Can you send a log file after having the APP frohen? (From within the
preferences)? I don't have that issue here...
Am 28.07.2015 5:31 nachm. schrieb "janusjanusjanus" <
notifications@github.com>:

**Comment by janusjanusjanus** [comment]
Sorry, no. Because I can´t access "preferences" due to the fact that when clicking on the wrench icon the app freezes.

**Comment by janusjanusjanus** [comment]
BTW: #939 and #940 affect different devices. #939: 4.1.1, #940: 4.2.2

**Comment by klassm** [comment]
Ah holdon - you're talking about the application preferences wrench and
not the connection preferences wrench?

Well this is kind of an old issue following over versions. There has
been one upgrade which kind of went wrong - Google somehow switched some
resources, resulting in that kind of behaviour for some users.

The only solution for this issue is to reinstall the app.

Sorry,
Matthias

Am 28.07.2015 um 18:52 schrieb janusjanusjanus:

**Comment by janusjanusjanus** [comment]
I did so. Now I have the same behaviour as in #939: I can´t save a new connection anymore.
BTW: That is also what one user has posted yesterday on google play; "Host Daten werden nicht gespeichert! Kann Daten eingeben, aber kann sie nicht speichern."

**Comment by klassm** [comment]
Well it might be some issue with a specific Android Version - I'll have to
check that on saturday.
Am 28.07.2015 7:08 nachm. schrieb "janusjanusjanus" <
notifications@github.com>:

**Comment by janusjanusjanus** [comment]
ok, thank you.
But please keep in mind that the problem affects at least two versions: 4.1.1 & 4.2.2.

**Comment by klassm** [comment]
Hi,

sorry, I forgot about that issue for some time. Do you still have that problem?

Matthias

**Comment by janusjanusjanus** [comment]
Thanks. I'm fine. It works.
